from enum import Enum


class Topic(str, Enum):
    LOCK_STATUS = 'NCSYS003_LOCK_STATUS',
    DOOR_STATUS = 'NCSYS003_DOOR_STATUS',
    SET_LOCK_CODE = 'NCSYS003_SET_LOCK_CODE',
    NODE_STATE = 'NCSYS003_NODE_STATE',
    SEND_OTP = 'NCSYS003_SEND_OTP',
    SMS_FROM_OPERATOR = 'NCSYS003_SMS_FROM_OPERATOR',
    REQUEST_DEFAULT_OTP = 'NCSYS003_REQUEST_DEFAULT_OTP',
    SET_DEFAULT_OTP = 'NCSYS003_SET_DEFAULT_OTP',


    def __str__(self) -> str:
        return self.value
